### ISSUE TITLE
Fails to decode

### ISSUE THREAD

**Issue by Amarok24** [ZbrDeev/base64.c#1]
Base64 string to decode:
SGVsbG8gd29ybGQ=

Current result:
He

Expected result:
Hello world

**Comment by ZbrDeev** [comment]
Hello,

Thanks for letting us know about the problem, we've solved it with a new push, you can delete version 1.0.0 and do a git pull origin main to get the new update and reinstall the library as written in the README.

Thank you,
ZbrDeev
